pipeline:
  name: account-level
  identifier: accountlevel
  tags: {}
  template:
    templateRef: account.Build_and_Deploy_to_K8s
    versionLabel: 1.0.0
    templateInputs:
      properties:
        ci:
          codebase:
            connectorRef: <+input>
            repoName: <+input>
            build: <+input>
      stages:
        - stage:
            identifier: Build_Image
            type: CI
            spec:
              execution:
                steps:
                  - step:
                      identifier: Build_Image
                      type: BuildAndPushDockerRegistry
                      spec:
                        connectorRef: <+input>
                        repo: <+input>
        - stage:
            identifier: Deploy_Image
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
  projectIdentifier: anmolpsandbox
  orgIdentifier: default
